### ISSUE TITLE
Replace dependency for faker

### ISSUE THREAD

**Issue by octo-kumo** [Sopur/Discord-user-bots#63]
Faker takes up 5Mb while only contributing to random user agents.

Using another library would be better, for example https://www.npmjs.com/package/rand-user-agent.

![image](https://github.com/user-attachments/assets/1fcbc0c3-ea7f-47b1-9e96-aff6257939db)

**Comment by Sopur** [comment]
I searched for random user agent packages for a while, but all of them, besides Faker, rely on an external source and a preset list to generate their user agents. The one you just suggested wouldn’t work because it fetches from a MySQL database that has to be run by the user to retrieve a list of user agents, then updates a JSON file to pick a random user agent. Ignoring the fact that this library wouldn’t work at all, I also refuse to have DUB fetch from an external database to get user agents or pick from an existing list, which could easily lead to DUB users being profiled. I suggest you review the source code of the libraries you recommend before suggesting them.
